apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "star.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
data:
  conf.json: |-
    {{- dict "version" .Chart.Version | toJson | nindent 4 }}
