{{- if .Values.frontend.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "star.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      {{- include "star.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "star.fullname" . }}-frontend-client: "true"
      {{- .Values.ingress.from | toYaml | nindent 6 }}
{{- end }}
