ingress:
  enabled: true
  host: orderer1.orderer.prod.star.eniblock.fr
  secretName: hlf--orderer1-tls

secrets:
  ord:
    cert: hlf--orderer1-idcert
    key: hlf--orderer1-idkey
    caCert: hlf--orderer1-cacert

    tls: hlf--orderer1-tls
    tlsRootCert: hlf--orderer1-tlsrootcert

releaseName: orderer1
