ingress:
  enabled: true
  host: orderer2.orderer.prod.star.eniblock.fr
  secretName: hlf--orderer2-tls

secrets:
  ord:
    cert: hlf--orderer2-idcert
    key: hlf--orderer2-idkey
    caCert: hlf--orderer2-cacert

    tls: hlf--orderer2-tls
    tlsRootCert: hlf--orderer2-tlsrootcert

releaseName: orderer2
