# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0


name: 'StarNetworkConsortium'
x-type: 'hlfv1'
x-loggingLevel: info

description: 'Star'
version: '1.0'
client:
  organization: 'DSO'
  mspid: 'DSOMSP'
  channelId: 'starnetwork'
  channelArtifacts:
    path: '/etc/star/channel-artifacts/'
  credentialStore:
    path: '/etc/star/credentials/dso'
  clientKey: '/etc/star/crypto-config/peerOrganizations/dso.star.com/users/Admin@dso.star.com/msp/keystore/Admin@dso.star.com_sk'
  clientCert: '/etc/star/crypto-config/peerOrganizations/dso.star.com/users/Admin@dso.star.com/msp/signcerts/Admin@dso.star.com-cert.pem'

  channels:
    - id: 'starnetwork'
      channelTx: 'channel.tx'
    - id: 'starnetworkorder'
      channelTx: 'channel-order.tx'

  chaincodes:
    - name: 'global'
      chaincodeId: 'global_chaincode'
      path: '/chaincode/global'
      version: '1.0'
      channelName: 'starnetwork'
      instantiator: false
    - name: 'order'
      chaincodeId: 'order_chaincode'
      path: '/chaincode/order'
      version: '1.0'
      channelName: 'starnetworkorder'
      instantiator: false

  tls:
    enabled: false
    clientKey: '/etc/star/crypto-config/peerOrganizations/dso.star.com/users/Admin@dso.star.com/tls/client.key'
    clientCert: '/etc/star/crypto-config/peerOrganizations/dso.star.com/users/Admin@dso.star.com/tls/client.crt'

  connection:
    timeout:
      peer:
        endorser: 120
        eventHub: 60
        eventReg: 3
      orderer: 30

organizations:
  DSO:
    mspid: DSOMSP
    peers:
      - peer0.dso.star.com
    certificateAuthorities:
      - ca.dso.star.com

orderers:
  orderer.star.com:
    url: grpc://orderer.star.com:7050
    urlGrpcs: grpcs://orderer.star.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.star.com
    tlsCACerts:
      path: /etc/star/crypto-config/ordererOrganizations/star.com/orderers/orderer.star.com/msp/tlscacerts/tlsca.star.com-cert.pem

peers:
  peer0.dso.star.com:
    url: grpc://peer0.dso.star.com:7051
    eventUrl: grpc://peer0.dso.star.com:7053
    urlGrpcs: grpcs://peer0.dso.star.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.dso.star.com
    tlsCACerts:
      path: /etc/star/crypto-config/peerOrganizations/dso.star.com/tlsca/tlsca.dso.star.com-cert.pem

certificateAuthorities:
  ca.dso.star.com:
    url: http://ca.dso.star.com:7054
    urlHttps: https://ca.dso.star.com:7054
    tlsCACerts:
      path: /etc/star/crypto-config/peerOrganizations/dso.star.com/tlsca/tlsca.dso.star.com-cert.pem
    httpOptions:
      verify: false
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.dso.star.com

identity:
  username: admin
  password: adminpw
