# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0


version: '3.7'
services:
  tso.star.server:
    container_name: tso.star.server
    build:
      context: .
    entrypoint:
      - grunt
      - dev
    healthcheck:
      test: curl --fail http://localhost:3000/api/readiness-probe
      interval: 10m
      timeout: 15s
      retries: 3
      start_period: 50s
    environment:
      - AUTHENTICATION_CONFIGURATION_PATH=/usr/src/app/config/authConfiguration.json
      - AUTHENTICATION_SECRET=/usr/src/app/config/secret.json
      - CONNECTION_PROFILE=/usr/src/app/config/connectionprofile/connectionprofile.tso.yaml
      - ORDERER_NAME=orderer.star.com
      - PEER_NAME=peer0.tso.star.com
      - CA_NAME=ca.tso.star.com
    volumes:
      - ./src:/usr/src/app/src
      - ./config/tso:/usr/src/app/config/
      - ./credentials:/etc/star/credentials
      - ./../resources/conf/infra/channel-artifacts:/etc/star/channel-artifacts
      - ./../resources/conf/infra/crypto-config:/etc/star/crypto-config
      - ../chaincode:/chaincode
    ports:
      - '3000:3000'
    networks:
      - star

  tso.star.client:
    build:
      context: ../client
    healthcheck:
      test: curl --fail http://localhost:4200
      interval: 10m
      timeout: 15s
      retries: 3
      start_period: 20s
    command: npm run ng -- serve --env=tso --host 0.0.0.0 --disable-host-check
    container_name: tso.star.client
    volumes:
      - ../client/src:/usr/src/app/src
    networks:
      - star

  tso.star.reverse_proxy:
    container_name: tso.star.reverse_proxy
    build:
      context: ../reverse-proxy
    volumes:
      - ../reverse-proxy/nginx.template:/etc/nginx/nginx.template
    environment:
      - CLIENT_NAME=tso.star.client
      - SERVER_NAME=tso.star.server
      - SERVER_PORT=3000
    ports:
      - '5000:5000'
    networks:
      - star

networks:
  star:
    name: star
