# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
---
Organizations:
    - &Consortium
        Name: Consortium
        ID: Consortium
        MSPDir: ../infra/crypto-config/ordererOrganizations/star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Consortium.member')"
            Writers:
                Type: Signature
                Rule: "OR('Consortium.member')"
            Admins:
                Type: Signature
                Rule: "OR('Consortium.admin')"
        OrdererEndpoints:
            - orderer.star.com:7050
            - orderer1.star.com:7050
            - orderer2.star.com:7050
            - orderer3.star.com:7050
            - orderer4.star.com:7050

    - &TSO
        Name: TSOMSP
        ID: TSOMSP
        MSPDir: ../infra/crypto-config/peerOrganizations/tso.star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TSOMSP.admin', 'TSOMSP.peer', 'TSOMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('TSOMSP.admin', 'TSOMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('TSOMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('TSOMSP.peer')"

        AnchorPeers:
        - Host: peer0.tso.star.com
          Port: 7051

    - &DSO
        Name: DSOMSP
        ID: DSOMSP
        MSPDir: ../infra/crypto-config/peerOrganizations/dso.star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DSOMSP.admin', 'DSOMSP.peer', 'DSOMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DSOMSP.admin', 'DSOMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DSOMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DSOMSP.peer')"

        AnchorPeers:
        - Host: peer0.dso.star.com
          Port: 7051

    - &THIRD
        Name: THIRDMSP
        ID: THIRDMSP
        MSPDir: ../infra/crypto-config/peerOrganizations/third.star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('THIRDMSP.admin', 'THIRDMSP.peer', 'THIRDMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('THIRDMSP.admin', 'THIRDMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('THIRDMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('THIRDMSP.peer')"

        AnchorPeers:
            - Host: peer0.third.star.com
              Port: 7051

    - &BSP
        Name: BSPMSP
        ID: BSPMSP
        MSPDir: ../infra/crypto-config/peerOrganizations/bsp.star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BSPMSP.admin', 'BSPMSP.peer', 'BSPMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BSPMSP.admin', 'BSPMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BSPMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('BSPMSP.peer')"

        AnchorPeers:
        - Host: peer0.third.star.com
          Port: 7051

    - &PRODUCER
        Name: PRODUCERMSP
        ID: PRODUCERMSP
        MSPDir: ../infra/crypto-config/peerOrganizations/producer.star.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('PRODUCERMSP.admin', 'PRODUCERMSP.peer', 'PRODUCERMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('PRODUCERMSP.admin', 'PRODUCERMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('PRODUCERMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('PRODUCERMSP.peer')"

        AnchorPeers:
            - Host: peer0.third.star.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true


Application: &ApplicationDefaults
    Organizations:
    Policies:
        # LifecycleEndorsement:
        #     Type: ImplicitMeta
        #     Rule: "MAJORITY Endorsement"
        # Endorsement:
        #     Type: ImplicitMeta
        #     Rule: "MAJORITY Endorsement"
        LifecycleEndorsement:
            Type: Signature
            Rule: "AND('TSOMSP.peer','DSOMSP.peer')"
        Endorsement:
            Type: Signature
            Rule: "AND('TSOMSP.peer','DSOMSP.peer')"
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft

    Addresses:
    - orderer.star.com:7050
    - orderer1.star.com:7050
    - orderer2.star.com:7050
    - orderer3.star.com:7050
    - orderer4.star.com:7050

    EtcdRaft:
        Consenters:
        - Host: orderer0.star.com
          Port: 7050
          ClientTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer.star.com/tls/server.crt
          ServerTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer.star.com/tls/server.crt
        - Host: orderer1.star.com
          Port: 7050
          ClientTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer1.star.com/tls/server.crt
          ServerTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer1.star.com/tls/server.crt
        - Host: orderer2.star.com
          Port: 7050
          ClientTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer2.star.com/tls/server.crt
          ServerTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer2.star.com/tls/server.crt
        - Host: orderer3.star.com
          Port: 7050
          ClientTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer3.star.com/tls/server.crt
          ServerTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer3.star.com/tls/server.crt
        - Host: orderer4.star.com
          Port: 7050
          ClientTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer4.star.com/tls/server.crt
          ServerTLSCert: ../infra/crypto-config/ordererOrganizations/star.com/orderers/orderer4.star.com/tls/server.crt

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    StarOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Consortium
            Capabilities: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
        Consortiums:
            StarNetworkConsortium:
                Organizations:
                - *TSO
                - *DSO
                - *THIRD
                - *BSP
                - *PRODUCER

    starnetwork:
        Consortium: StarNetworkConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *TSO
                - *DSO
                - *THIRD
                - *BSP
                - *PRODUCER

    starnetworkorder:
        Consortium: StarNetworkConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *TSO
                - *DSO
