# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

version: "3.7"
services:
  ca.third.star.com:
    image: hyperledger/fabric-ca:1.5.2
    container_name: ca.third.star.com
    environment:
      - FABRIC_CA_DB_FILE=/var/hyperledger/fabric-ca-server/db/fabric-ca-server.db
    command: sh -c 'rm $$FABRIC_CA_DB_FILE; mkdir -p /var/hyperledger/fabric-ca-server/db;
      fabric-ca-server start -b admin:adminpw --db.datasource $$FABRIC_CA_DB_FILE -d
      --cafiles /etc/hyperledger/ca-config/third.star.com.yaml
      --cafiles /etc/hyperledger/ca-config/producer.star.com.yaml
      --cafiles /etc/hyperledger/ca-config/bsp.star.com.yaml'
    ports:
      - "10054:7054"
    volumes:
      - ./../resources/conf/infra/crypto-config/peerOrganizations/third.star.com/ca/:/etc/hyperledger/fabric-ca-third-server-config
      - ./../resources/conf/infra/crypto-config/peerOrganizations/bsp.star.com/ca/:/etc/hyperledger/fabric-ca-bsp-server-config
      - ./../resources/conf/infra/crypto-config/peerOrganizations/producer.star.com/ca/:/etc/hyperledger/fabric-ca-producer-server-config
      - ./../resources/conf/infra/ca-config/:/etc/hyperledger/ca-config
    networks:
      - star

  # ca.bsp.star.com:
  #   image: hyperledger/fabric-ca:1.5.2
  #   container_name: ca.bsp.star.com
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.bsp.star.com
  #     - FABRIC_CA_SERVER_TLS_ENABLED=false
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bsp.star.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.bsp.star.com_sk
  #     - FABRIC_CA_DB_FILE=/var/hyperledger/fabric-ca-server/db/fabric-ca-server.db
  #     - FABRIC_CA_CONF_FILE=/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml
  #   ports:
  #     - "9054:7054"
  #   volumes:
  #     - ../resources/conf/infra/crypto-config/peerOrganizations/bsp.star.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #   command: sh -c 'rm $$FABRIC_CA_DB_FILE ; mkdir -p /var/hyperledger/fabric-ca-server/db ; fabric-ca-server start --ca.certfile $$FABRIC_CA_SERVER_TLS_CERTFILE --ca.keyfile $$FABRIC_CA_SERVER_TLS_KEYFILE -c $$FABRIC_CA_CONF_FILE -b admin:adminpw --db.datasource $$FABRIC_CA_DB_FILE -d'
  #   networks:
  #     - star

  # ca.producer.star.com:
  #   image: hyperledger/fabric-ca:1.5.2
  #   container_name: ca.producer.star.com
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.producer.star.com
  #     - FABRIC_CA_SERVER_TLS_ENABLED=false
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.star.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.star.com_sk
  #     - FABRIC_CA_DB_FILE=/var/hyperledger/fabric-ca-server/db/fabric-ca-server.db
  #     - FABRIC_CA_CONF_FILE=/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml
  #   ports:
  #     - "10054:7054"
  #   volumes:
  #     - ../resources/conf/infra/crypto-config/peerOrganizations/producer.star.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #   command: sh -c 'rm $$FABRIC_CA_DB_FILE ; mkdir -p /var/hyperledger/fabric-ca-server/db ; fabric-ca-server start --ca.certfile $$FABRIC_CA_SERVER_TLS_CERTFILE --ca.keyfile $$FABRIC_CA_SERVER_TLS_KEYFILE -c $$FABRIC_CA_CONF_FILE -b admin:adminpw --db.datasource $$FABRIC_CA_DB_FILE -d'
  #   networks:
  #     - star

  peer0.third.star.com:
    image: hyperledger/fabric-peer:2.3.3
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    container_name: peer0.third.star.com
    depends_on:
      - cdbp0.third.star.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - BASE_DOCKER_NS=hyperledger
      - DOCKER_NS=hyperledger
      - ARCH=amd64
      - PROJECT_VERSION=2.3.3
      - BASE_VERSION=2.3
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=star
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer0.third.star.com
      - CORE_PEER_ADDRESS=peer0.third.star.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=cdbp0.third.star.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.third.star.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.third.star.com:7051
      - CORE_PEER_LOCALMSPID=THIRDMSP
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.third.star.com
    volumes:
      # - /var/run/:/host/var/run/
      - ../resources/conf/infra/crypto-config/peerOrganizations/third.star.com/peers/peer0.third.star.com/msp:/etc/hyperledger/fabric/msp
      - ../resources/conf/infra/crypto-config/peerOrganizations/third.star.com/peers/peer0.third.star.com/tls:/etc/hyperledger/fabric/tls
      - ../chaincode/global:/usr/src/app/chaincode/global
      - ../resources/conf/infra/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
      - ../resources/conf/generate-artifacts/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../sampleBuilder:/sampleBuilder
    command: peer node start
    ports:
      - "10051:7051"
      - "10053:7053"
    networks:
      - star

  cdbp0.third.star.com:
    image: couchdb:3.1.1
    container_name: cdbp0.third.star.com
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    networks:
      - star

  cli-peer0.third.star.com:
    container_name: cli-peer0.third.star.com
    image: hyperledger/fabric-tools:2.3.3
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.third.star.com:7051
      - CORE_PEER_NAME=peer0.third.star.com
      - ORDERER_NAME=orderer.star.com
      - CORE_PEER_LOCALMSPID=THIRDMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/third.star.com/peers/peer0.third.star.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/third.star.com/peers/peer0.third.star.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/third.star.com/peers/peer0.third.star.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/third.star.com/users/Admin@third.star.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    # command: >
    #   bash -c " \
    #     set -e; \
    #     sleep 10; \
    #     # peer chaincode install -n global_chaincode -l node -v 1.0 -p /usr/src/app/chaincode/global; \
    #     peer channel fetch 0 -o orderer.star.com:7050 -c starnetwork --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/star.com/orderers/orderer.star.com/msp/tlscacerts/tlsca.star.com-cert.pem; \
    #     peer channel join -b starnetwork_0.block; \
    #     echo 'Joined Channel.'; \
    #     echo 'Done!'; \
    #     /bin/bash
    #     "
    volumes:
      # - /var/run/:/host/var/run/
      - ../resources/conf/infra/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ../chaincode:/usr/src/app/chaincode
      - ../resources/conf/infra/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - star

networks:
  star:
    name: star
