apiVersion: v1
kind: Service
metadata:
  name: {{ include "star.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "star.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
