# Copyright (C) 2020, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

OrdererOrgs:
  - Name: Orderer
    Domain: star.com
    CA:
      Country: FR
      Province: IDF
      Locality: Paris
    Specs:
      - Hostname: orderer
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4

PeerOrgs:
  - Name: TSO
    Domain: tso.star.com
    EnableNodeOUs: true
    CA:
      Country: FR
      Province: IDF
      Locality: Paris
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: DSO
    Domain: dso.star.com
    EnableNodeOUs: true
    CA:
      Country: FR
      Province: IDF
      Locality: Paris
    Template:
      Count: 1
    Users:
      Count: 1

  # - Name: THIRD
  #   Domain: third.star.com
  #   EnableNodeOUs: true
  #   CA:
  #     Country: FR
  #     Province: IDF
  #     Locality: Paris
  #   Template:
  #     Count: 1
  #   Users:
  #     Count: 0

  - Name: BSP
    Domain: bsp.star.com
    EnableNodeOUs: true
    CA:
      Country: FR
      Province: IDF
      Locality: Paris
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PRODUCER
    Domain: producer.star.com
    EnableNodeOUs: true
    CA:
      Country: FR
      Province: IDF
      Locality: Paris
    Template:
      Count: 1
    Users:
      Count: 1

