apiVersion: v1
kind: Secret
metadata:
  name: local-ca-key-pair
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "ca.crt" | b64enc }}
  tls.key:  {{ .Files.Get "ca.key" | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local
spec:
  ca:
    secretName: local-ca-key-pair
