apiVersion: v1
kind: Secret
metadata:
  name: {{ include "star.keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "admin-password" "management-password" }}
  {{- include "star.automaticSecret" (list . (include "star.keycloak.fullname" .) $keys) | indent 2 }}
