{{ $name := printf "%s-db" (include "star.keycloak.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "star.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keys := list "postgresql-password" "postgresql-postgres-password" }}
  {{- include "star.automaticSecret" (list . $name $keys) | indent 2 }}
