name: fast-forward

on:
  issue_comment:
    types: [created]

jobs:
  fast-forward:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: '***target_base*** successfully fast forwarded to ***source_head***!'
          failure_message: 'Fast forward failed!'
          staging_branch: 'staging'
          production_branch: 'prod'
