mail:
    username: ENC[AES256_GCM,data:ay8vXOG/highyvdqZubVfg==,iv:Djl6pssa4sLeQWN455YhH+LChKbqmcw7b5WHodjks34=,tag:aDxgBe168LYkcffMqtJqkg==,type:str]
    password: ENC[AES256_GCM,data:sJyR71fkjZQwOHpKcijeReQtGw==,iv:mCAN0Of3/tQ6TO2q12INLj4+euj+cDKUWx/wfVMvjYw=,tag:WpZEWPZ/EI/HKLoCnqr+iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8yvhdyuw858pyc3pjylwn0388vnfeqe2sxh3yxt2pr47mjrdf7qpk2nnh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb3Zlc0VncHFRVmMvVGkv
            Z2krMUs5OXczMFZKS0Y0OEx0d0p0VHJaNDJzCkwxdTQ4T1dkTVc0U2pmOHVPRVpo
            dUFUN1ZiZXVwdkoydFF2dFVWNlhYcmsKLS0tIGgwZDR5T1JZWjhrNXZiQnkwUUhx
            T3pHbmtabm5GanQvS1NRQ3ZxcFBMWlUK15xWNx1OvNO0X72uwMm25BwYX24cVoaW
            g7Z6L6+WDbFxLAyByfinArwgOtJQCbXa0tu4YWQ6qK0vxmndYtHdZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T09:26:21Z"
    mac: ENC[AES256_GCM,data:Fs8vhYxvi/cRrn95mTIbMEjlrIs40sRO480Ip2giy9K6PNz+i2iXAcplc02Iz//rnwrhBwcaRLCiKN+r86nmAQG/uapEPPc5RZS5inLhI/86umdbOYTvkI2Vm7QhqIiyj7YKkKGcdCjF1OyCfrti8CyB34S3IuRlyQHtQ4DdYa8=,iv:mVxwinZxlvNn64ub/GasgZ+MO28N8UxPleBwCvjBNzU=,tag:X4pYH+et++2Q3cwiP2U0zw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
