keycloak:
    configurator:
        secrets:
            users:
                - username: ENC[AES256_GCM,data:mfy2H1v/EqE=,iv:HGCKQeEJPUwejK5EwIaxxwA/sBn6RUeTcai+nc6Lpa8=,tag:3ChFjngU/vvfrmAEUNbDww==,type:str]
                  first_name: ENC[AES256_GCM,data:EHK3vJdG,iv:63W89V/UvayyztWJifst0qs8y+o9c4t91gbo5ugPFqg=,tag:KPPS6LPmZNnoTZ1Xf5hTTA==,type:str]
                  last_name: ENC[AES256_GCM,data:/bDM29ITZw==,iv:sjgvYQjpwzu5cnfbeGSRfwlUTkp7yhTBHadDDNVeGGQ=,tag:hyrjcLO2XY70jVq33JOQiw==,type:str]
                  email: ENC[AES256_GCM,data:iuIa94SkHon1cMBI79/kzoUk3e7gEL81Zb/DIsl6,iv:M9+z6b1tVo9p9vNEsbklPHIeJfORyv17TRv7Y8mqlHY=,tag:k58yV5LKceI4GXKmUIWATw==,type:str]
                  initial_password: ENC[AES256_GCM,data:ZC+hzaWM2Yi6H7GVIFAk4+Em9vk=,iv:vlCpL6jHDeo+YoroPyt7E2omL3SCcATcDcpjly3IVxU=,tag:jMGvOVFwM2HW4Jf4AWTPtw==,type:str]
                  systemOperatorMarketParticipantMrid: ENC[AES256_GCM,data:YvXeBUsnITyE0GhfovSzmw==,iv:Z3x2dMXmBBpI5rMO7tpQXz2Hd9hMHaWlHDr+W4xed2I=,tag:sdef3gTXrzhHV0dIFSBFHA==,type:str]
                - username: ENC[AES256_GCM,data:YXJ6vxC8,iv:hFjPO7a1rI2I4z0B3Cpy8xV+p9SnLoArCeHptC/RWVM=,tag:hvAmpwKQ2KP/BKo11U/uiA==,type:str]
                  first_name: ENC[AES256_GCM,data:lJpT5A==,iv:CDqT5OINv9LxjJAVCEq+tu+fcUPAsNyximHjVrW8q8M=,tag:bVBQ2dkQfAtEhb4Cl5c5wg==,type:str]
                  last_name: ENC[AES256_GCM,data:cQilvdY=,iv:EpqKLDwJ9FpdcpezIsP79nRjTm7HzQMx2oA1AelbyTc=,tag:zfGvx4q73QrweSGGyzde6Q==,type:str]
                  email: ENC[AES256_GCM,data:7NU4M5tI0J7hV4rJH+w6vCq25hcrMoKO+pKPXMuVUf0=,iv:hRNyfXhtlYZBIgMAD2dSEtOhTJsiFpGArobhIlfujq0=,tag:Dntik8BQXgSLG6+ufi9txQ==,type:str]
                  initial_password: ENC[AES256_GCM,data:ZC+hzaWM2Yi6H7GVIFAk4+Em9vk=,iv:vlCpL6jHDeo+YoroPyt7E2omL3SCcATcDcpjly3IVxU=,tag:jMGvOVFwM2HW4Jf4AWTPtw==,type:str]
                  systemOperatorMarketParticipantMrid: ENC[AES256_GCM,data:YvXeBUsnITyE0GhfovSzmw==,iv:Z3x2dMXmBBpI5rMO7tpQXz2Hd9hMHaWlHDr+W4xed2I=,tag:sdef3gTXrzhHV0dIFSBFHA==,type:str]
                - username: ENC[AES256_GCM,data:+VQmYatFplf30w==,iv:rSY80c+eBILFuHKXhMkUcAuIi6aN7A/8HCfJlmQpd7o=,tag:yB5aq6azL4t8QF2q9hvCXg==,type:str]
                  first_name: ENC[AES256_GCM,data:yyU0s/1yA9DDJA==,iv:gTcvfjKDIOMI+KllfnXsIBygwOzVaGttYpPmbvUYXFk=,tag:cXtYMF/tsSiJ2f/ldfGNcg==,type:str]
                  last_name: ENC[AES256_GCM,data:fUcuukn8es+B,iv:e6Iyutzm+ytBF9zDW/nMgEF4we1V7R5h/zMjuNJnGmA=,tag:K4J3iDuI8I7D5yqTPpzIuA==,type:str]
                  email: ENC[AES256_GCM,data:8cS/3b5m5CrdeP+vobr5rQEeJ35T8g8fF/W4cE9Kpbt4,iv:RJvb9LYdUvdOHAyMBkQMe1Vi8giXTQ4qLWM9Cp9Q41k=,tag:u8mmwo2waj2xnbo2FX8wNg==,type:str]
                  initial_password: ENC[AES256_GCM,data:ZC+hzaWM2Yi6H7GVIFAk4+Em9vk=,iv:vlCpL6jHDeo+YoroPyt7E2omL3SCcATcDcpjly3IVxU=,tag:jMGvOVFwM2HW4Jf4AWTPtw==,type:str]
                  systemOperatorMarketParticipantMrid: ENC[AES256_GCM,data:YvXeBUsnITyE0GhfovSzmw==,iv:Z3x2dMXmBBpI5rMO7tpQXz2Hd9hMHaWlHDr+W4xed2I=,tag:sdef3gTXrzhHV0dIFSBFHA==,type:str]
                - username: ENC[AES256_GCM,data:/bOaNwwWl9I=,iv:ckXAqFn8iyZyjNw9lA2MEUAzf0TqAV4QypelTUpsbKM=,tag:fGAUcnhggV4Tj1DTy7WYHg==,type:str]
                  first_name: ENC[AES256_GCM,data:EsJRbI5ymA==,iv:aTdj3qinx4+/gAYnB8GSwkDkPjD0zxvUC+7ft/9LIKs=,tag:RIgUPrOqhrtpJfkvou4qlA==,type:str]
                  last_name: ENC[AES256_GCM,data:aplLJlLeJQ==,iv:uLcQsWknPTcfwdD634HWtxQvOhBKwYyDiGn+RsUmOFg=,tag:DGPat7ZzahtVTDR+4k6glg==,type:str]
                  email: ENC[AES256_GCM,data:mVDPogCtNMRNaFB1vsELLGtGNW3UTQJeTYOcH33V,iv:DVzCNYWcmEPOsc31cxHVvhkbMm5YVASYA6rDlkR9+qA=,tag:Si1alYQqLZajz7VfxYBJxA==,type:str]
                  initial_password: ENC[AES256_GCM,data:ZC+hzaWM2Yi6H7GVIFAk4+Em9vk=,iv:vlCpL6jHDeo+YoroPyt7E2omL3SCcATcDcpjly3IVxU=,tag:jMGvOVFwM2HW4Jf4AWTPtw==,type:str]
                  systemOperatorMarketParticipantMrid: ENC[AES256_GCM,data:YvXeBUsnITyE0GhfovSzmw==,iv:Z3x2dMXmBBpI5rMO7tpQXz2Hd9hMHaWlHDr+W4xed2I=,tag:sdef3gTXrzhHV0dIFSBFHA==,type:str]
                - username: ENC[AES256_GCM,data:xbfEeCXMwZBGKQ==,iv:MqMHuLEBO8QWaWiZOdBlXOeejkmkdrOonGVDV5lM6sU=,tag:MvQrK9HLEJL+tAcEVdGRGw==,type:str]
                  first_name: ENC[AES256_GCM,data:H2tEFTpbNQ==,iv:EAYEh7TLzyageGNnar3P3Tu+MiWj637JSIBzzKVvqjM=,tag:/MmpVHmgXgkwsu0kdUzaJQ==,type:str]
                  last_name: ENC[AES256_GCM,data:Rsf7YW/Fzr/C,iv:+yMswimsZ7/9T2VRyjJBwO6WNacwhzBH+U3Rck4aE0k=,tag:1UQm47dqBw5rn3n1YjEEnw==,type:str]
                  email: ENC[AES256_GCM,data:sGmoiuSLqhovqt3+IgGqed5Z0uaq4jmXpQ==,iv:sKHwNhyspb4AKYjk4Lwb6Y/JWAOvZywEpvVayvGqvmA=,tag:6L2VlbgaAH/yzGi+TvHIQA==,type:str]
                  initial_password: ENC[AES256_GCM,data:pNpYsncqefapuH8BDaLjPdiKVCg=,iv:XAhfoZV2ax4/FFsEUsFceBwaEOjY5qm8PIlSAQynBEE=,tag:4m6eFuGOK4FeHR/QTnuAhw==,type:str]
                  producerMarketParticipantMrid: ENC[AES256_GCM,data:3+3WSLq7Oi8WMjiL403LUQ==,iv:mS0kjGABSIA8ghkKOckM6+1UI8BL0k38ivWB5wpD+TM=,tag:xqGUiAtOR5ms7qatPPiOBg==,type:str]
                - username: ENC[AES256_GCM,data:szWzXUt2ziY=,iv:iiw5IpArNc3theQzdom9qZhmwaNkk9wZDtmPWz/CpqA=,tag:M09Hlroz9ci1NKtvJBJ8wQ==,type:str]
                  first_name: ENC[AES256_GCM,data:h0o5kQe7LSjo,iv:Oq/f7WoA43pFjB4F+iuyj4ubDbWkWXkkuiDPoDDeuRM=,tag:pdgC02ryJpHiagdrao0ZsQ==,type:str]
                  last_name: ENC[AES256_GCM,data:a8zGWdzUFg==,iv:20JBuqVs+YRWZwr2Ci5iomScEEvj6E/WmjHDoyQ1TJE=,tag:hWQHil1Dsv8SUFYl41YgRw==,type:str]
                  email: ENC[AES256_GCM,data:tejqEKO/o8a/v0hmaHaaN0TgmrMdeOtTJwI=,iv:CmTt1Wa+lKF97VIFHLflu/U3dqknpmcEia6Fc/EIWXc=,tag:kLauz+6ygtBBA/U08BjQcA==,type:str]
                  initial_password: ENC[AES256_GCM,data:uqG/RBneLcxRebrrwKcOeoYfKME=,iv:d1RJTsO8ahqRxSWDOz8IVBQr9080Y0rhlEOvQY3GHic=,tag:40b+bRrAHPwuFkijjGhrtw==,type:str]
                  producerMarketParticipantMrid: ENC[AES256_GCM,data:kE80N+nz9z5jxplF142moQ==,iv:jF2vJHrasTve28P0vLmu4/tGYUjU1GyFKkO9u+g0tQk=,tag:neFsl2j7BlYYx7cuknIXrw==,type:str]
                - username: ENC[AES256_GCM,data:rPFVPJQB,iv:PWl2VKu6xyYLiJcbsjNJef3+vwsmMNupT5Zyt1/FJN0=,tag:+UGtGLrFswhJtVQUJBUdnQ==,type:str]
                  first_name: ENC[AES256_GCM,data:m0iYcBs=,iv:s6pe6cxcVHzAsIDjUw2v3rUXBiBMqGZbricYPo40T6k=,tag:a3K6wQ8sUXOAmAihdYdyVw==,type:str]
                  last_name: ENC[AES256_GCM,data:vn9FwUY=,iv:Cm/inH7LdWb8L4O8DX/OHnnQH1tnG7+s50ymnvRkA5U=,tag:cu1cqMCYPu6LJlbFHqyW/g==,type:str]
                  email: ENC[AES256_GCM,data:wiD1ey+QE8dNxtKnDku77VB5sg==,iv:ujz7U2bHEWKnoAR2tpWCtyAMbiKq2gxWLAj93XPKmkg=,tag:r1e+7z6wCKdzKR8VpssLwQ==,type:str]
                  initial_password: ENC[AES256_GCM,data:wZKvlkpbDq7J2qmC1sXRXyoan3w=,iv:LEdTX9FQtD2echquEgKWWoYyBf1CZaL8SteFj9uzD3A=,tag:S/zdT3Ap24v/eNCCYDwNbg==,type:str]
                  producerMarketParticipantMrid: ENC[AES256_GCM,data:3+3WSLq7Oi8WMjiL403LUQ==,iv:mS0kjGABSIA8ghkKOckM6+1UI8BL0k38ivWB5wpD+TM=,tag:xqGUiAtOR5ms7qatPPiOBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d90vedmsexhgqdstj9mep6sz6r2hu6a65g75m86uvsdjr4z02q4snskvvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV0ZhMjNwQVFSMllSVmcy
            RWhnUG82clR5UjlLMVk1SWhheU5lTkRtNDJZCjBkT0M2bm9MMlVlQ21uM3VoeFJN
            UC8wQVNud042UjFNN3dyTGdNQjJKaDAKLS0tIE9HVkgvNzkvaTFpdDNISWtGNkFr
            MDlyMVN4ZjExMXRScW9tOXNMZm96VjAKH8sq6y5Xh6MhL7C91G8UBNzspXiNB8KP
            LFtY6KRvAQtScHT8xew0aHtUfuT7pB9FUZZGY3G4YrFRrXvmJGbczg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T10:18:10Z"
    mac: ENC[AES256_GCM,data:z44VK3sVZD879uVAN26oEiEm+NuR4IrfeowqYjz9R3gR+zvoqqt5dzxnfEcNnRqsYZd7sJXhxD75Zjah858u2ViAPlr0a7XkVcEYZuD6McP+sqlCpsgrClgbfx1vwdxkLSosKVNPWFwz1rslVwzWJamSadgQ2PSTSfjSkqs87tw=,iv:C7zWEd7NDHAYOhVyb5e0b5IISWWlkCx2RaXAbIQhSSM=,tag:Lfjfq8Jl5wui42yQgVgm5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
