ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "25"
  host: "producer.star.eniblock.fr"
backend:
  peerConnectionOrganization: producer
  instance: producer
keycloak:
  ingress:
    host: "producer.star.eniblock.fr"