ingress:
  enabled: true
  host: "enedis.testing.star.eniblock.fr"

frontend:
  replicaCount: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "app.kubernetes.io/component"
            operator: In
            values:
            - "frontend"
        topologyKey: "kubernetes.io/hostname"

backend:
  replicaCount: 2
  peerConnectionOrganization: enedis
  instance: dso
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "app.kubernetes.io/component"
            operator: In
            values:
            - "backend"
        topologyKey: "kubernetes.io/hostname"

keycloak:
  ingress:
    host: "enedis.testing.star.eniblock.fr"
